[package]
name = "gbc_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.4.1"
num-traits = "0.2.15"
int-enum = "0.5.0"
rfd = "0.10.0"
